# Generated by Django 3.1 on 2020-10-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions_and_Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=350, verbose_name='Вопрос')),
                ('answers', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос Ответ',
                'db_table': 'questions_and_answers',
                'ordering': ['questions'],
            },
        ),
    ]
