# Generated by Django 3.1 on 2020-10-04 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=350, verbose_name='Заголовок')),
                ('project_img_one', models.ImageField(blank=True, upload_to='uploads/images/%Y/%m/%d/')),
                ('project_img_two', models.ImageField(blank=True, upload_to='uploads/images/%Y/%m/%d/')),
                ('project_img_three', models.ImageField(blank=True, upload_to='uploads/images/%Y/%m/%d/')),
                ('publication_date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Дата публикации')),
                ('answers', models.TextField(verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Анонсы',
                'db_table': 'news',
                'ordering': ['publication_date'],
            },
        ),
    ]
