# Generated by Django 3.1 on 2020-10-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['publication_date'], 'verbose_name': 'Анонс', 'verbose_name_plural': 'Анонсы'},
        ),
        migrations.AlterModelOptions(
            name='questions_and_answers',
            options={'ordering': ['questions'], 'verbose_name': 'Вопрос Ответ', 'verbose_name_plural': 'Вопрос Ответ'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='answers',
        ),
        migrations.AddField(
            model_name='news',
            name='post',
            field=models.TextField(default='def', verbose_name='Анонс'),
            preserve_default=False,
        ),
    ]
