# Generated by Django 3.1 on 2020-10-09 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=350, verbose_name='Заголовок')),
                ('coast', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('pakeges', models.TextField(verbose_name='Пакет услуг')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
                'db_table': 'prices',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.prices', verbose_name='Цена на ивент)'),
        ),
    ]
