# Generated by Django 3.1 on 2020-10-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_auto_20201010_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prices',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AddField(
            model_name='news',
            name='heading_for_img_one',
            field=models.CharField(max_length=350, null=True, verbose_name='Заголовок к первой фотографии'),
        ),
        migrations.AddField(
            model_name='news',
            name='heading_for_img_three',
            field=models.CharField(max_length=350, null=True, verbose_name='Заголовок к третьей фотографии'),
        ),
        migrations.AddField(
            model_name='news',
            name='heading_for_img_two',
            field=models.CharField(max_length=350, null=True, verbose_name='Заголовок ко второй фотографии'),
        ),
        migrations.AddField(
            model_name='news',
            name='post_for_img_one',
            field=models.CharField(max_length=350, null=True, verbose_name='Описание к первой фотографии'),
        ),
        migrations.AddField(
            model_name='news',
            name='post_for_img_three',
            field=models.CharField(max_length=350, null=True, verbose_name='Описание к третьей фотографии'),
        ),
        migrations.AddField(
            model_name='news',
            name='post_for_img_two',
            field=models.CharField(max_length=350, null=True, verbose_name='Описание ко второй фотографии'),
        ),
        migrations.AlterField(
            model_name='news',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.prices', verbose_name='Цена на ивент)'),
        ),
    ]
